### ISSUE TITLE
[Feature] Add hero image overlay filters

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#124]
Something like...

```
{% if page.header.overlay_filter contains "rgba" %}
  {% capture overlay_filter %}{{ page.header.overlay_filter }}{% endcapture %}
{% elsif page.header.overlay_filter %}
  {% capture overlay_filter %}rgba(0, 0, 0, {{ page.header.overlay_filter }}){% endcapture %}
{% endif %}
```

Credits to Michael Rose in [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/) for the [code snippet](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_includes/page__hero.html#L19-L23).

**Comment by Phlow** [comment]
What will it do? Can you add an image?

**Comment by ghost** [comment]
Sure! Please see live demo at [habd.as](http://habd.as). The hero images have 0.3-0.5 percent alpha rgba linear gradients applied, applied in such away it simply makes the background solid but a little bit darker -- without having to do any image editing.

In order to utilize the property one must use an image tag with a background gradient. After fooling around I was not able to get it to work well with Backstretch.  I'll close this but it would be a nice enhancement for the next version. Please reopen or roadmap if you like it!

**Comment by Phlow** [comment]
When I finish *Feeling Responsive V. 2.0* and I don't know when, *Backstretch* won't be there anymore, because you can solve the problem with pure CSS. If you're curious, have a look at [*Simplicity*](https://github.com/Phlow/simplicity).

Than it will be easy, to use your idea.

PS: And I didn't really thankyou for your help and commits. Thankyou :)
