### ISSUE TITLE
Sitemap Gotchas

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#127]
I noticed some gotchas worth pointing out regarding the custom sitemap:

- Unexpectedly outputs items with `sitemap: false` in them, such as the [`search` page](https://github.com/Phlow/feeling-responsive/blob/594b5d8e464d2911eb049909e10b83b57943dcb8/pages/search.md).
- Outputs `404.html`, which most individuals will not want indexed.
- Does not adapt to collections automatically, and manual updates can easily be forgotten.

The custom `sitemap.xml` file indicates `jekyll-sitemap` does not allow custom `priority` or `changefreq`, which seems moot given the two items were removed [as documented](https://github.com/jekyll/jekyll-sitemap/blob/056609988dbd9a3325e9226a0afbc35d90bb9146/History.markdown#080--2015-02-03) in the `jekyll-sitemap` CHANGELOG.

As a result, we should consider removing the custom sitemap and working towards standard gem usage. Meanwhile, those wanting a workaround can remove the custom `sitemap.xml` and `sitemap_custom.xml` files, install the [`jekyll-sitemap` gem](https://github.com/jekyll/jekyll-sitemap) and refactor affected content files.

**Comment by Phlow** [comment]
You mean, we should delete the old template and use the standard gem instead, right?

**Comment by ghost** [comment]
Indeed. I did so myself and found the Gem automatically handles collections and I believe it will weather better over time being supported by the fine Jekyll core team.

**Comment by Phlow** [comment]
OK. One more thing todo :) 👍

**Comment by ghost** [comment]
For continuity here are the [accessibility and wishlist items](https://github.com/Phlow/feeling-responsive/issues/120#issuecomment-264234976) for roadmap consideration from a separate issue.

**Comment by ghost** [comment]
@Phlow [my client](http://comfusionllc.com/clients/chicago-gang-history/) is experiencing rapid growth with this template and I've promised to take him to [PageSpeed 100](https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/) once he received 50 new organic users for a week straight, which he just did. Could you start a new branch for the port and link me to a quick and dirty roadmap so I can start pushing the redesign forward? Thank you. 😃

**Comment by Phlow** [comment]
A great website. I am proud, that you used my theme…

OK, now to the urgent request :)

Currently I have no time developing *Feeling Responsive* any faster, because firstly I have to earn some money… ;) But I uploaded the work I've already done.

- First of all, it's now based on Foundation Version 6.2.4, but there is already a new one out.
- Than I integrated lunr.js for search – not included in the topbar right know, but you can test it on <https://phlow.github.io/feeling-responsive-v2/search/>
- Than I wanted to get rid of backstretch and replace it with a CSS-only-solution. That's why the images in the header don't show up. I use a CSS-only-header already on my other theme *Simplicity* [have a look](https://phlow.github.io/simplicity/header-image/)
- and the *the biggest* change is typography and a more minimalistic look
- ah, and I sorted *_includes*
- and I want got get rid of the icon-font › faster now with inline svgs
- and maybe I forgot some things on the way…
- ah… I forgot › You now can choose different color schemes and set easily your favorite fonts via _config.yml_

Just have a look and play around with it… It has – in my opinion – some great new ideas and I learned a lot in the meantime playing around with Jekyll a little bit more :)

Forgot the new repository › <https://github.com/Phlow/feeling-responsive-v2>

**Comment by Phlow** [comment]
ah, I wrote down some changes in changelog already…

    Kicked own variable {{ site.urlimg }} to make it easier
    Instead of {{ site.url }}{{ site.baseurl }} we use the new absolure_url-filter like this https://phlow.github.io/feeling-responsive-v2/changelog/

**Comment by ghost** [comment]
Just what I was looking for. Thanks, boss. I don't have your eye for design but I can get us to the 10 yard line. PRs to follow.

**Comment by Phlow** [comment]
I am not your boss ;) Great that you help.

**Comment by inetbiz** [comment]
@Phlow & @ghost I installed the jekyll-sitemap gem and ran into issues with the sample page for media player. See https://travis-ci.com/inetbiz/semantic-seo-jekyll/builds/108620183 Not sure where or what has to change?
