### ISSUE TITLE
Can't see small grids in template grid and colors

### ISSUE THREAD

**Issue by bsde1245** [Phlow/feeling-responsive#143]
Can't see small grids in template grid and colors in mobile  view. Please fix.

**Comment by ghost** [comment]
@justinechacko hello! could you send along a screenshot or code snippet and more clearly state your problem? Otherwise head to StackOverflow and try posting there for a better response rate and faster feedback.

**Comment by bsde1245** [comment]
https://s28.postimg.org/feaoqz51p/Screenshot_from_2017-03-29_11-10-31.png

In your demo theme, go to template>grid and colors. In mobile mode we can't see grid columns some times can see larger ones only. In screenshot there is only two grid boxes, but in web view there is small 3 and smallest 4 boxes are there. Did you follow?

**Comment by Phlow** [comment]
This is how *Feeling Responsive* uses the grid on this special site. The theme is built upon Foundation framework. To use the grid, check out the documentation › [Foundation 5.5.3](http://foundation.zurb.com/sites/docs/v/5.5.3/)

**Comment by Phlow** [comment]
In my view, more than 2 columns on mobile devices makes no sense.

**Comment by ghost** [comment]
@justinechacko Here's a direct link: http://foundation.zurb.com/sites/docs/v/5.5.3/components/grid.html

You'll likely want to adjust your layout using some of the responsive helpers. Thanks for the additional detail and reporting your concern.

**Comment by ghost** [comment]
Thinking this through further what if more than two columns caused offscreen content the user had to swipe for? Like Medium Series' only more like PhotoSwipe. The new Carousel. Oh man. If only I had more time!! :)~

**Comment by TWiStErRob** [comment]
@justinechacko Just to reiterate, because it's not obvious from the above comments: this is how that particular page was designed, just read the [source code](https://github.com/Phlow/feeling-responsive/blame/gh-pages/_posts/design/2014-09-13-grid.md#L18-L32). The content *on this particular page* for large screens is different than for small screens.
![image](https://cloud.githubusercontent.com/assets/2906988/24586540/ce37917c-179b-11e7-928f-b47f16b76a13.png)
It's entirely up to the user of the theme to build those grids within the content of the page.

Even if you have more than 12 as the sum of column sizes (which Foundation wants), you'll end up with wrapped, but **not hidden**, content:
![image](https://cloud.githubusercontent.com/assets/2906988/24586559/26806c32-179c-11e7-96a1-e8c0147c14da.png)
![image](https://cloud.githubusercontent.com/assets/2906988/24586558/1e038332-179c-11e7-921e-4f0f5e71774e.png)
