### ISSUE TITLE
Probably a simple, dumb mistake

### ISSUE THREAD

**Issue by krionical** [Phlow/feeling-responsive#153]
I have been tinkering with this theme on and off for probably three weeks trying to achieve one simple thing: I want to change the header to my own image. My process is to open one of the existing headers, use another photo match the size of the header, rename it, and stick it in the images folder. I then change index.md in the pages root folder to reflect the new name of the image. When I re-load the page, I invariably get the text, but no image. I can switch to any of the other images that come with the repo, but I can't seem to get it to use the one I add. As I said, it is probably something terribly simple I am overlooking, so if you can help out with it, it would sure help me, and I imagine other people who might have a similar issue.

**Comment by wsteenbeek** [comment]
Did you solve this already? I had the exact same question. I believe the 'backstretch' function is the culprit, as it attempts to find all images on `phlow.github.io` instead of your own site url:

I did what you did (make a new picture with the exact same dimensions and filetype as existing ones, and tried to change the header image), and I try to get the site to work offline first (so I'm working with 'jekyll serve' in terminal), and this is what I found in the produced html:

```
<script>
    $("#masthead").backstretch("https://phlow.github.io/feeling-responsive/images/header_testnew.jpg", {fade: 700});
    $("#masthead-with-text").backstretch("https://phlow.github.io/feeling-responsive/images/header_testnew.jpg", {fade: 700});
</script>
```

Obviously, when on my own computer it should be `http://127.0.0.1:4000` instead of `https://phlow.github.io`. Changing the url in `_config.yml` doesn't help.

So I haven't solved it. Anyone...?

**Comment by Phlow** [comment]
Did you change 

~~~
url: 'https://phlow.github.io'
urlimg: 'https://phlow.github.io/feeling-responsive/images/'
~~~

in `_config.yml`


Because in `_footer_scripts.html`

these variables are used like this:

~~~
{% if page.header.image_fullwidth %}
<script>
    $("#masthead").backstretch("{{ site.urlimg }}{{ page.header.image_fullwidth }}", {fade: 700});
    $("#masthead-with-text").backstretch("{{ site.urlimg }}{{ page.header.image_fullwidth }}", {fade: 700});
</script>
{% endif %}
~~~
