### ISSUE TITLE
code blocks not very pretty

### ISSUE THREAD

**Issue by prudhomm** [Phlow/feeling-responsive#156]
Thank you for your work on feeling-responsive. It is very nice and powerful.
I am trying to use it for a software website using asciidoc

I want to write math and c++ code blocks(`<pre>`), however the code blocks are not very nice.  It seems that you fixed it in the `-v2` version. 
Could it be possible to fix that too in this repository ?

**Comment by prudhomm** [comment]
@Phlow, If you don't think it should be fixed, let me know how to change code blocks on our website.
Thank you very much in advance.
PS: I would be glad (a bit ) to contribute financially to your work

**Comment by TWiStErRob** [comment]
Hi @prudhomm, you can find a customized version of the theme here:
https://github.com/TWiStErRob/twisterrob.github.io -> http://www.twisterrob.net

Here's an example of code blocks I implemented:
http://www.twisterrob.net/blog/2016/02/blog-formatting.html#code ([source](https://github.com/TWiStErRob/twisterrob.github.io/blame/master/_posts/2016-02-16-blog-formatting.md#L43-L85))

Interesting parts of site for customizing code blocks:
https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_config.yml#L141-L178
https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_sass/_06_typography.scss#L235-L319
https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_sass/_11_syntax-highlighting.scss

**Comment by prudhomm** [comment]
very nice !
I will look at your work asap and let you know how we are doing !

**Comment by prudhomm** [comment]
thanks a lot for the tips and bravo for your website !

**Comment by abulka** [comment]
I tried to incorporate the changes made by @TWiStErRob into this jekyll template by
- replacing the `/* Code` section in `_sass/_06_typography.scss` with the new one
- replacing `_sass/_11_syntax-highlighting.scss` with the new one
- adding the new `kramdown:` section to `_config.yml`
- renaming the `highlight` key to be spelt `highlighter` in `_config.yml`

but the result was not much better, in fact looked worse because the code styling seems designed for a 'dark' theme, so my markdown

````
{% highlight ruby linenos %}
def foo
    puts 'foo'
end
{% endhighlight %}

{% highlight ruby %}
def foo
    puts 'foo'
end
{% endhighlight %}

```ruby
def foo
    puts 'foo'
end
```
````

results in

![image](https://user-images.githubusercontent.com/11467530/77243301-9f158480-6c5c-11ea-968a-a2423f584ffd.png)

Perhaps I missed something (very hard to exactly extract and diff what has changed).

**Comment by TWiStErRob** [comment]
@arnaud-m did it work for you? I couldn't find a code block on your website by browsing around.

**Comment by arnaud-m** [comment]
@TWiStErRob Yes, it somehow worked even if we did not find a beautiful light theme ...
You can have a look to code blocks in this [post](http://i3s.unice.fr/master-info/divers/modele-syllabus/
).

We have not spent a lot of time for designing the theme because we have published only a few code blocks. From memory, we took it from this [gallery](http://jwarby.github.io/jekyll-pygments-themes/languages/python.html).

**Comment by TWiStErRob** [comment]
@abulka I think you got it working, but you need to adjust your color scheme, like @arnaud-m. The colors I'm using are my custom scheme I use in all my code editors. I think I only use GFM (` ```lang `), and decided to not use linenos (if it requires a line number reference in explanation, then the example is too complex), so didn't bother styling them. You need to look at the HTML structure and style that part yourself.

**Comment by TWiStErRob** [comment]
@arnaud-m I recommend you give a try to:
http://www.twisterrob.net/blog/2016/02/blog-formatting.html#code-block-with-title ([source](https://github.com/TWiStErRob/twisterrob.github.io/blame/dc545cae9c0e64ed7ad47e5b79d90736be8a7401/_posts/2016-02-16-blog-formatting.md#L62-L68))

**Comment by arnaud-m** [comment]
@TWiStErRob nice dark theme
We will try to improve our light theme in the next weeks.
I did not know that we can add title to block code. That's nice.

**Comment by mpelleau** [comment]
Finally, we chose the `rand01` syntax highlighting (example [here](http://shjs.sourceforge.net/)). As the all site is light we prefer to stick with a light syntax highlight.

@TWiStErRob we took the examples given on [your page](http://www.twisterrob.net/blog/2016/02/blog-formatting.html#normal-code-block) in [ours](http://i3s.unice.fr/master-info/divers/modele-syllabus/)

@abulka It is important to set the variables `$code-background-color` and `$code-color` in the `_01_settings_colors.scss` file, the first one set the color of the background and the second the default color of the text in the code. See @TWiStErRob's [file](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_sass/_01_settings_colors.scss) Hope this helps
