### ISSUE TITLE
I meet a problem..

### ISSUE THREAD

**Issue by elicec** [Phlow/feeling-responsive#49]
I use your theme feeling -responsive，but，when
i edit _config.yml -------

url: 'https://phlow.github.io/feeling-responsive'

to My ---------
url: 'https://elicec.github.io/feeling-responsive'

my site become that [elicec.github.io](elicec.github.io)
![](http://i.imgur.com/CkEJUst.png)
why??

**Comment by TWiStErRob** [comment]
If you want to host that repo as your main one (username.GitHub.io) you have to specify the full address (similar to CNAME file). The url in config has to match the URL your site is displayed as, see for example: https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_config.yml#L31

You can easily find out what's the problem if you look at your browsers Network tab in Developer tools when the page has apparent no styles. Usually it's a 404 and by looking at the URL you can see what's wrong with it.

If you have username.GitHub.io address as URL you may have extra redirects for every resource, because of CNAME, which will result in bad user experience.
