### ISSUE TITLE
$topbar-bg-color in colors/globals .scss files

### ISSUE THREAD

**Issue by evildmp** [Phlow/feeling-responsive#52]
Hi, I'm learning Jekyll, Sass and Foundation all at the same time, so I may have missed something basic. 

Anyhow, https://github.com/Phlow/feeling-responsive/blob/gh-pages/_sass/_01_settings_colors.scss#L74

```
$topbar-bg-color: #fff;
```

(which seems the obvious place to change/define that colour) never gets used because of https://github.com/Phlow/feeling-responsive/blob/gh-pages/_sass/_04_settings_global.scss#L1375

```
$topbar-bg-color: #fff;
```

As I say this may be just that I have misunderstood something.

**Comment by TWiStErRob** [comment]
That's correct. I've found the same. There may be others too, all `topbar-*` may have an uncommented line in global.

**Comment by evildmp** [comment]
@TWiStErRob are you saying that this is correct and expected, or are you agreeing that it looks like a bug?

**Comment by TWiStErRob** [comment]
I agree that the problem exists. I've had the same experience of learning several languages/frameworks at once (don't forget the mighty Liquid :) and maybe Ruby) which doesn't help much.

From SASS perspective it's expected because you're simply overriding a variable, that's one of the reasons to use SASS. So it's working as intended.

From Feeling Responsive perspective, it's not really a bug. If you're customising the theme's looks you have to be aware of all the settings scss files. An obvious fix - to make it less tricky and more convenient - would be to comment out the line global.scss and have that distributed to the users of the theme.

I suggest you review those files and make a pull request yourself.
