### ISSUE TITLE
Recommended means to change colour scheme?

### ISSUE THREAD

**Issue by funkypenguin** [Phlow/feeling-responsive#58]
Hey, loving this theme!

I've been wondering how to change the colour theme on certain elements, for example the code highlights. I tried replacing _sass/_11_syntax-highlighting.scss with a solarized theme (https://gist.github.com/qguv/7936275), but it didn't seem to work as expected. The green background for the code highlights remains, at the least.

Thanks!
D

**Comment by TWiStErRob** [comment]
That should be it though to change the text color, which you managed to do. There's also a Code section in `typography`, which defines a background color based on `$code-background-color` in `settings_colors`.

In general to find out where a style is coming from:
- run `serve` with `_config_dev.yml` (instructions inside)  
  needed to have `site.sass.line_numbers: true`
- this will result in comments above each style in generated css
- open page in Chrome/Firefox and open inspector/dev tools/firebug
- Inspect an element you want to change the style of
- Find the CSS style you're interested in and click the line source (upper right):
  ![image](https://cloud.githubusercontent.com/assets/2906988/10691836/bea8dd6e-798c-11e5-87c1-e111ac1b7e05.png)
- Read the comment which .scss file it is coming from

This only works well on non-minified sources, that's why you need the dev config.

**Comment by hpigot** [comment]
I was trying to make similar changes and found everything I was looking for in `/_sass/_01_settings_colors.scss`. In particular, I was looking to change the green/turquoise used in the navigation bar.

The green code highlighting you mention is found on line 120, `$code-background-color: scale-color($secondary-color, $lightness: 70%);` which links back to `$ci-6: #A1D044;     // green`. 

In this file you can change the entire color scheme of Feeling Responsive by altering the `Corporate Identity Colorpalette` line 29-34.  Some good alternative color schemes can be found on [https://color.adobe.com/]().

**Comment by Phlow** [comment]
Thankyou @hpigot
