### ISSUE TITLE
navbar link for blog does not display as active

### ISSUE THREAD

**Issue by clhenrick** [Phlow/feeling-responsive#60]
When visiting another part of the site, the navbar displays the corresponding page's link as active, as in "documentation" here:
![screen shot 2015-11-18 at 9 17 10 am](https://cloud.githubusercontent.com/assets/161748/11243429/fb847b00-8dd5-11e5-8753-d734457fe4c1.png)

However, when on "blog" the navbar link does not display as active:
![screen shot 2015-11-18 at 9 22 38 am](https://cloud.githubusercontent.com/assets/161748/11243453/1f893cc0-8dd6-11e5-8da7-020fcb2b4cc1.png)

I think this likely has to do with the logic evaluating `link.url` and `page.url` in `_navigation.html` and the way the blog page is set up in other directory outside of `pages/`.

**Comment by clhenrick** [comment]
The issue may be fixed if in the front matter of `/blog/index.html` you add `permalink: "/blog/"`

**Comment by TWiStErRob** [comment]
What is the `page.url` and `link.url` for `/blog/` without the permalink? (I'm lazy to compile it ;)

**Comment by Phlow** [comment]
Interesting. On Localhost I don't have that problem. I followed your instructions but it doesnt work on Github Pages... :( Currently I have no clue.

**Comment by clhenrick** [comment]
I'm using Jekyll -v 2.5.3 on my local machine. Perhaps it has something to do with differences between Jekyll versions?

**Comment by Phlow** [comment]
I have no idea. I don't like it this way. Maybe we get the solution soon.

**Comment by TWiStErRob** [comment]
I rewrote that part for my site, see for example how the submenu is highlighted as well on http://www.twisterrob.net/blog/category/dev/ it's a little more complicated than current, see code at https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_includes/navigation.html

**Comment by TWiStErRob** [comment]
@Phlow it's possibly a `site.url` vs `site.baseurl` issue.

**Comment by Phlow** [comment]
@TWiStErRob Puh, your solution looks difficult. I don't have the time to dig it right now.

When I rewrote the code a little bit last week or the week before, I went crazy.

It should be so simple to just compare the actual `page.url` to the url in the __data/_navigation.html_ like this:

```
{% if site.data.navigation.url == page.url %} class="active"{% endif %}
```

But as soon as I moved the comparison into a for loop it broke. That was my understanding. I had not the nerve to ask for help on https://talk.jekyllrb.com/

Currently I have lots to do. Maybe I come back to this. It's not my priority right now.

In my opion it has nothing to do with `site.url` vs `site.baseurl` because it is no part of the comparison. Or do I miss something?

**Comment by TWiStErRob** [comment]
Yeah I know mine is a little over the top, especially with the specials, but it highlights deep :)

`site.data.navigation.url` looks like a static variable, it doesn't change. As far as I know `site.data.navigation` is a map or list. The current `link.url==page.url` seems to be good, maybe there's a trailing `/` in one of them or something that's being weird.

**Comment by ghost** [comment]
Here's how Hugo manages menuing deep taxonomies, which could be a pattern worth looking at during the F6 port: https://gohugo.io/extras/menus#adding-content-to-menus
