### ISSUE TITLE
Color customization should be included in Getting started

### ISSUE THREAD

**Issue by TWiStErRob** [Phlow/feeling-responsive#82]
Re #81: I think at least
- _01_settings_colors.scss
- _02_settings_typography.scss

should be included as step 3 and 4 at https://phlow.github.io/feeling-responsive/getting-started/ because it is a very frequent thing to change the color theme.

I made some changes to the other scss files to reduce hard-code values and use more of the defined named colors from the above two files. I also needed a few changes to handle dark background (see http://www.twisterrob.net/blog/2015/06/Jekyll-hacks-for-development.html as it contains a lot of different elements in the post), I'll try to put a PR in the future.

**Comment by Phlow** [comment]
You're right, it should be included.

I will put it on my list… I do the theme in my spare time. That's why it takes sometimes, some time ;)

I made a new theme in the last months with a better approach to more structured and a more understandable .scss-hierarchy. If you have some time, check it out:

https://github.com/Phlow/simplicity/tree/gh-pages/_sass

There I tried not to use any _hard-code values_.

With foundation, _Feeling Responsive_ is very bloated. And it's very difficult to simplify it for people not knowing about Foundation, SCSS and CSS and HTML in general.
