### ISSUE TITLE
Github pages occasionally truncates generated page

### ISSUE THREAD

**Issue by norbertpotocki** [Phlow/feeling-responsive#98]
Hi,

I'm having some trouble with deploying the template to github pages. I reported it against the [github/pages-gem#298](https://github.com/github/pages-gem/issues/298) repository. Have you encountered a similar behavior before?

Here's the copy-paste of the issue:

---

Hi,

I found a significant inconsistency between pages generated locally and pushed to github which I can't explain. Long story short - some pages are being truncated when published to github. At the same time they work perfectly on a local jekyll installation. I hope you can help me find the root cause. Let me know how can I help more in resolving this.
### This issue affects
- [YES] The site generated by GitHub Pages
- [NO] Building sites locally
### What did you do (e.g., steps to reproduce)
- install ruby 2.3.1 using rbenv (also tried with 2.1.7-github1 - same result)
- install jekyll as per https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
- clone the repo: https://github.com/cfg4j/cfg4j.github.io
- run jekyll: bundle exec jekyll serve --config _config.yml
- open: http://localhost:4000/releases/release_4_4_0/ and scroll to the very bottom of the page
- open: http://www.cfg4j.org/releases/release_4_4_0/  and scroll to the very bottom of the page
- see how the hosted page is malformed

It's even more severe for this page (95% of the content is missing):
http://www.cfg4j.org/releases/latest/
vs.
http://localhost:4000/releases/latest/
### What did you expect to happen?

I expected both sites to look identically.
### What happened instead?

The hosted (github pages) page misses large chunks of html.
### Additional information
- Link to the live site (if applicable): http://www.cfg4j.org/releases/release_4_4_0/
- Link to the source repo (if applicable):
  --- https://raw.githubusercontent.com/cfg4j/cfg4j.github.io/master/_posts/releases/2016-05-07-release_4_4_0.md
  --- layout for this page: https://github.com/cfg4j/cfg4j.github.io/blob/master/_layouts/release.html

**Comment by TWiStErRob** [comment]
Here's what I did:
- Download the source code of http://www.cfg4j.org/releases/release_4_4_0/
- Clone your repo and serve it and download the local version of the same page
- Diff them, the result: ![image](https://cloud.githubusercontent.com/assets/2906988/16132657/6605096a-3414-11e6-86c7-85bcb79870c3.png)
  So the online version is missing some stuff and some of the HTML elements are messed up. I know that this theme uses `compress` and that's probably the difference
- `set JEKYLL_ENV=production` and run serve again -> the issue is reproduced locally.
- Since this kind-of confirmed that the culprit is `compress` (note the `compress_html.ignore.envs: [development]` setting in your `_config.yml`) I went ahead and diffed the `compress.html` layout in the theme and your repo, and boy do they differ:
  ![image](https://cloud.githubusercontent.com/assets/2906988/16132904/8b06f196-3415-11e6-9062-dead10e1b1c4.png)
  The problem is that your website editor was too eager to format the source of that file, but it doesn't really have a clue about the Liquid template language. I suggest that you chose an editor that support these languages or turn off auto-formatting, because both Liquid and `compress` are extremely sensitive to whitespaces. The problem is that Liquid's strings end at new line, and the formatting put a new line character before `<pre` leaving it dangling. That's why the `production` generated site starts with `<pre<!doctype`.

Sublime Text has a Liquid plugin that gives basic support. You can also try and editor that supports Django, because the two languages are really similar.

**Comment by norbertpotocki** [comment]
Thanks @TWiStErRob! Restoring the original formatting fixed the issue.
